import { useEffect, useState } from "react";

type Registration = { registration: { displayName: string } | null };
type Module = { id: string; displayName: string; runtimeAttributes: Record<string, unknown>; capabilities: string[] };
type Power = { summary: { activePowerDrawKw: number; solarGenerationKw: number; netPowerKw: number; solarIrradianceWPerM2: number; solarCondition: string } };
const base = (import.meta.env.VITE_HABITAT_API_BASE_URL || "/api").replace(/\/$/, "");
async function get<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(base + path, { ...init, headers: { "Content-Type": "application/json", ...init?.headers } });
  const raw = await response.text();
  let body: unknown;
  try { body = raw ? JSON.parse(raw) : undefined; } catch { throw new Error(`${path} returned invalid JSON: ${raw.slice(0, 120)}`); }
  if (!response.ok) throw new Error((body as { error?: { message?: string } })?.error?.message || `Habitat API error (${response.status})`);
  return body as T;
}

export function Dashboard() {
  const [registration, setRegistration] = useState<Registration["registration"]>(null); const [modules, setModules] = useState<Module[]>([]); const [power, setPower] = useState<Power["summary"]>(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [dark, setDark] = useState(true); const [name, setName] = useState(""); const [confirm, setConfirm] = useState(false); const [custom, setCustom] = useState("");
  const refresh = async () => { setError(""); const results = await Promise.allSettled([get<Registration>("/registration"), get<{ modules: Module[] }>("/modules"), get<Power>("/power")]); const [r, m, p] = results; if (r.status === "fulfilled") setRegistration(r.value.registration); if (m.status === "fulfilled") setModules(m.value.modules); if (p.status === "fulfilled") setPower(p.value.summary); const failed = results.find(result => result.status === "rejected"); if (failed?.status === "rejected") setError(failed.reason instanceof Error ? failed.reason.message : "Unable to load part of Habitat state."); };
  useEffect(() => { void refresh(); }, []);
  const tick = async (tickCount: number) => { setBusy(true); try { const result = await get<{ modules: Module[]; summary: Power["summary"] }>("/ticks", { method: "POST", body: JSON.stringify({ tickCount }) }); setModules(result.modules); setPower(result.summary); } catch (e) { setError(e instanceof Error ? e.message : "Tick failed."); } finally { setBusy(false); } };
  const toggle = async (module: Module) => { setBusy(true); try { const status = module.runtimeAttributes.status === "online" ? "offline" : "online"; await get(`/modules/${encodeURIComponent(module.id)}`, { method: "PATCH", body: JSON.stringify({ runtimeAttributes: { ...module.runtimeAttributes, status } }) }); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Module update failed."); } finally { setBusy(false); } };
  const register = async () => { setBusy(true); try { await get("/registration", { method: "POST", body: JSON.stringify({ displayName: name }) }); setName(""); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Registration failed."); } finally { setBusy(false); } };
  const unregister = async () => { setBusy(true); try { await get("/registration", { method: "DELETE" }); setConfirm(false); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Unregister failed."); } finally { setBusy(false); } };
  return <main data-theme={dark ? "dark" : "light"}><header><div><span className="eyebrow">HABITAT / OPERATIONS</span><h1>{registration?.displayName || "Habitat control"}</h1></div><button onClick={() => setDark(!dark)}>{dark ? "Light" : "Dark"} mode</button></header>{error && <aside className="error">{error} <button onClick={() => void refresh()}>Retry</button></aside>}{!registration && <section className="panel"><span className="eyebrow">REGISTER HABITAT</span><div className="module"><input aria-label="Habitat name" value={name} onChange={e => setName(e.target.value)} placeholder="Habitat name" /><button disabled={busy || !name.trim()} onClick={() => void register()}>Register</button></div></section>}{registration && <section className="panel"><div className="panel-title"><span className="eyebrow">REGISTRATION</span>{confirm ? <span>Unregister this Habitat? <button onClick={() => void unregister()}>Confirm</button> <button onClick={() => setConfirm(false)}>Cancel</button></span> : <button onClick={() => setConfirm(true)}>Unregister habitat</button>}</div></section>}<section className="hero"><div><span className="eyebrow">SYSTEM STATUS</span><strong className={registration ? "online" : "offline"}>{registration ? "REGISTERED" : "NOT REGISTERED"}</strong></div><div className="ticks">{[1, 60, 600, 3600].map(n => <button disabled={busy} onClick={() => void tick(n)} key={n}>Advance {n === 3600 ? "1 hour" : n === 600 ? "10 min" : n === 60 ? "1 min" : "1 tick"}</button>)}<input aria-label="Custom ticks" inputMode="numeric" value={custom} onChange={e => setCustom(e.target.value.replace(/\D/g, ""))} placeholder="ticks" /><button disabled={busy || !custom || Number(custom) < 1} onClick={() => void tick(Number(custom))}>Advance custom</button></div></section>{power && <section className="grid">{[["Generation", power.solarGenerationKw, "kW"], ["Consumption", power.activePowerDrawKw, "kW"], ["Net power", power.netPowerKw, "kW"], ["Solar", power.solarIrradianceWPerM2, "W/m²"]].map(([label, value, unit]) => <article key={label as string}><span>{label}</span><b>{Number(value).toFixed(2)} <small>{unit}</small></b></article>)}</section>}<section className="panel"><div className="panel-title"><span className="eyebrow">MODULES</span><span>{modules.length} active records</span></div>{modules.length === 0 ? <p className="muted">No modules available.</p> : modules.map(m => <div className="module" key={m.id}><div><b>{m.displayName}</b><span>{m.id}</span></div><span className={m.runtimeAttributes.status === "online" ? "online" : "offline"}>{String(m.runtimeAttributes.status || "unknown")} · {typeof m.runtimeAttributes.powerDrawKw === "number" ? `${m.runtimeAttributes.powerDrawKw} kW` : "power --"}</span><button disabled={busy} onClick={() => void toggle(m)}>{m.runtimeAttributes.status === "online" ? "Set offline" : "Set online"}</button></div>)}</section></main>;
}
